/// Integration tests for chia-vdf-verify using real test vectors from chiavdf.
///
/// Test vectors generated by building chiavdf (C++/GMP) and running:
///   seed = "test_seed_chia" (14 bytes)
///   disc_bits = 512
///   x = generator form (a=2, b=1) = the 0x08 BQFC encoding
///   iters = 100
///   y = x^(2^100) with discriminant D

use chia_vdf_verify::verifier::check_proof_of_time_n_wesolowski;
use chia_vdf_verify::discriminant::create_discriminant;
use chia_vdf_verify::proof_common::{
    serialize_form, deserialize_form, fast_pow_form_nucomp, get_b, fast_pow,
};
use chia_vdf_verify::form::Form;
use chia_vdf_verify::nucomp::{nucomp, nudupl};
use chia_vdf_verify::reducer::reduce;
use chia_vdf_verify::integer::{from_bytes_be, num_bits};
use chia_vdf_verify::bqfc::BQFC_FORM_SIZE;
use chia_vdf_verify::primetest::is_prime_bpsw;
use num_bigint::BigInt;
use num_traits::{Signed, Zero};

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i+2], 16).unwrap())
        .collect()
}

/// Test vector generated by chiavdf C++ implementation.
/// seed = b"test_seed_chia", disc_bits=512, iters=100
/// x = generator form (BQFC encoding 0x08...)
const ITERS: u64 = 100;
const D_BYTES_HEX: &str = "d0cb181074454b32a0e0fc5e65a1d7625ea43756eaa8de13a9c750c79f7aa60151f065cd5775516159c28713c1e74ced6520f8f5c55129f32f865b28cf7fe8e7";
const X_S_HEX: &str = "08000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const PROOF_BLOB_HEX: &str = "020020417eb39c4e14954a817af644fc13d086c26dddab8afea12415b5e685f7883f5740ba01cb75220081c8aba7854cbd52010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

fn get_discriminant() -> BigInt {
    let d_bytes = hex_decode(D_BYTES_HEX);
    -from_bytes_be(&d_bytes)
}

/// Full integration test: verify a real Wesolowski proof from chiavdf.
#[test]
fn test_verify_real_proof_depth0() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(result, "check_proof_of_time_n_wesolowski failed on known-good proof");
}

/// Verify that the discriminant we generate matches the test vector.
#[test]
fn test_discriminant_matches_testvector() {
    let seed = b"test_seed_chia";
    let d_rust = create_discriminant(seed, 512);
    let d_expected = get_discriminant();
    assert_eq!(d_rust, d_expected,
        "Rust discriminant doesn't match C++ discriminant");
}

/// Verify the discriminant is negative and ≡ 1 (mod 8).
#[test]
fn test_discriminant_properties() {
    let seed = b"test_seed_chia";
    let d = create_discriminant(seed, 512);
    assert!(d.is_negative(), "D must be negative");

    use num_integer::Integer;
    let r = d.mod_floor(&BigInt::from(8));
    assert_eq!(r, BigInt::from(1), "D must be ≡ 1 (mod 8)");

    assert_eq!(num_bits(&d), 512, "D must have exactly 512 bits");

    let p = -d;
    assert!(is_prime_bpsw(&p), "magnitude of D must be prime");
}

/// Verify x (generator form) can be deserialized.
#[test]
fn test_deserialize_generator_form() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).expect("failed to deserialize x");
    assert_eq!(x.a, BigInt::from(2u32), "generator form: a should be 2");
    assert_eq!(x.b, BigInt::from(1u32), "generator form: b should be 1");
}

/// Verify y can be deserialized and has correct discriminant.
#[test]
fn test_deserialize_y_form() {
    let d = get_discriminant();
    let proof_blob = hex_decode(PROOF_BLOB_HEX);
    let y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE])
        .expect("failed to deserialize y");

    // Check discriminant: b^2 - 4ac = D
    let disc = &y.b * &y.b - BigInt::from(4) * &y.a * &y.c;
    assert_eq!(disc, d, "y form has wrong discriminant");
    assert!(y.is_reduced(), "y must be reduced");
}

/// Verify form exponentiation preserves discriminant.
#[test]
fn test_form_exponentiation_preserves_discriminant() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).unwrap();
    let l = Form::compute_l(&d);

    for &exp in &[0u64, 1, 2, 10, 50] {
        let result = fast_pow_form_nucomp(&x, &d, &BigInt::from(exp), &l);
        let disc = &result.b * &result.b - BigInt::from(4) * &result.a * &result.c;
        assert_eq!(disc, d, "discriminant changed after exponentiation by {}", exp);
        assert!(result.is_reduced(), "form not reduced after exponentiation by {}", exp);
    }
}

/// Property: x^0 = identity.
#[test]
fn test_zero_exponentiation_is_identity() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).unwrap();
    let l = Form::compute_l(&d);

    let result = fast_pow_form_nucomp(&x, &d, &BigInt::zero(), &l);
    assert_eq!(result.a, BigInt::from(1u32), "x^0 should be identity (a=1)");
    assert_eq!(result.b, BigInt::from(1u32), "x^0 should be identity (b=1)");
}

/// Property: x^1 = x.
#[test]
fn test_one_exponentiation_is_self() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).unwrap();
    let l = Form::compute_l(&d);

    let result = fast_pow_form_nucomp(&x, &d, &BigInt::from(1u32), &l);
    let mut x_reduced = x.clone();
    reduce(&mut x_reduced);
    assert_eq!(result, x_reduced, "x^1 should equal x");
}

/// Property: nudupl preserves discriminant.
#[test]
fn test_nudupl_discriminant() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).unwrap();
    let l = Form::compute_l(&d);

    let mut f = x;
    for _ in 0..10 {
        f = nudupl(&f, &d, &l);
        reduce(&mut f);
        let disc = &f.b * &f.b - BigInt::from(4) * &f.a * &f.c;
        assert_eq!(disc, d, "nudupl changed discriminant");
    }
}

/// Property: nucomp is commutative (f*g = g*f after reduction).
#[test]
fn test_nucomp_commutativity() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let x = deserialize_form(&d, &x_s).unwrap();
    let l = Form::compute_l(&d);

    let y = nudupl(&x, &d, &l);
    let mut y = y;
    reduce(&mut y);

    let mut fg = nucomp(&x, &y, &d, &l);
    reduce(&mut fg);

    let mut gf = nucomp(&y, &x, &d, &l);
    reduce(&mut gf);

    assert_eq!(fg, gf, "nucomp must be commutative");
}

/// Property: reduction is idempotent.
#[test]
fn test_reduction_idempotent() {
    let d = get_discriminant();
    let proof_blob = hex_decode(PROOF_BLOB_HEX);
    let y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE]).unwrap();

    // y is already reduced (from deserialize)
    let mut y2 = y.clone();
    reduce(&mut y2);
    assert_eq!(y, y2, "reduction should be idempotent on already-reduced form");
}

/// Property: BQFC round-trip for generator and identity forms.
#[test]
fn test_bqfc_roundtrip_special_forms() {
    let d = get_discriminant();
    let d_bits = num_bits(&d);

    // Identity
    let mut identity = Form::identity(&d);
    let bytes = serialize_form(&mut identity, d_bits);
    let f2 = deserialize_form(&d, &bytes).unwrap();
    assert_eq!(identity.a, f2.a);
    assert_eq!(identity.b, f2.b);

    // Generator
    let mut gen = Form::generator(&d);
    let bytes = serialize_form(&mut gen, d_bits);
    let f2 = deserialize_form(&d, &bytes).unwrap();
    assert_eq!(gen.a, f2.a);
    assert_eq!(gen.b, f2.b);
}

/// Property: BQFC round-trip for the y form from the test vector.
#[test]
fn test_bqfc_roundtrip_y_form() {
    let d = get_discriminant();
    let d_bits = num_bits(&d);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let original_bytes = &proof_blob[..BQFC_FORM_SIZE];
    let y = deserialize_form(&d, original_bytes).unwrap();

    let mut y_for_ser = y.clone();
    let re_serialized = serialize_form(&mut y_for_ser, d_bits);
    assert_eq!(re_serialized, original_bytes,
        "BQFC serialization of y should match original bytes");
}

/// Verify that GetB matches: B computed from (x, y) matches what's embedded
/// in proof verification (the proof is only valid with the correct B).
#[test]
fn test_get_b_deterministic() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let mut x = deserialize_form(&d, &x_s).unwrap();
    let mut y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE]).unwrap();

    let b1 = get_b(&d, &mut x, &mut y);
    let b2 = get_b(&d, &mut x, &mut y);
    assert_eq!(b1, b2, "GetB must be deterministic");
    assert!(is_prime_bpsw(&b1), "B must be prime");
    assert_eq!(num_bits(&b1), 264, "B must be 264 bits");
}

/// FastPow correctness: 2^100 mod B.
#[test]
fn test_fast_pow_correctness() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let mut x = deserialize_form(&d, &x_s).unwrap();
    let mut y = deserialize_form(&d, &proof_blob[..BQFC_FORM_SIZE]).unwrap();
    let b = get_b(&d, &mut x, &mut y);

    let r = fast_pow(ITERS, &b);
    // r = 2^100 mod B
    assert!(r < b, "r must be < B");
    assert!(!r.is_zero() || ITERS == 0, "r should not be 0 for typical cases");
}

// Second test vector: seed = "chia-vdf-rust", iters = 200
const ITERS2: u64 = 200;
const D_BYTES2_HEX: &str = "c3ef34d02017540ef26d88057bbfc778da12ed572b99f8707834ed344577c210b1f9287f54a536913177bf5880a4a51b6bfa42445f3fbcd082b695e38c2066d7";
const PROOF_BLOB2_HEX: &str = "030033205ea6d1ab367757073029f1462eb2fcc79749871d0b576f7a392adac84f56f46100e477d59353376f82a3eb56720d010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

/// Second test vector: different seed, 200 iterations.
#[test]
fn test_verify_real_proof_second_vector() {
    let d = {
        let d_bytes = hex_decode(D_BYTES2_HEX);
        -from_bytes_be(&d_bytes)
    };
    let x_s = hex_decode(X_S_HEX); // same x (generator form)
    let proof_blob = hex_decode(PROOF_BLOB2_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS2, 0);
    assert!(result, "second test vector verification failed");
}

/// Wrong iters should fail verification.
#[test]
fn test_wrong_iters_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS + 1, 0);
    assert!(!result, "wrong iters should fail verification");
}

/// Wrong proof blob size should fail.
#[test]
fn test_wrong_blob_size_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let proof_blob = hex_decode(PROOF_BLOB_HEX);

    // Truncate
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob[..100], ITERS, 0);
    assert!(!result, "truncated blob should fail");

    // Extend with garbage
    let mut bad_blob = proof_blob.clone();
    bad_blob.push(0);
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &bad_blob, ITERS, 0);
    assert!(!result, "extended blob should fail");
}

/// Corrupted y bytes should fail verification.
#[test]
fn test_corrupted_y_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX);

    // Corrupt a byte in y
    proof_blob[5] ^= 0x01;
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(!result, "corrupted y should fail verification");
}

/// Corrupted proof bytes should fail verification.
#[test]
fn test_corrupted_proof_fails() {
    let d = get_discriminant();
    let x_s = hex_decode(X_S_HEX);
    let mut proof_blob = hex_decode(PROOF_BLOB_HEX);

    // The proof for this test vector serializes to the identity form (first byte 0x04).
    // Corrupt byte 0 of the proof to turn it into a non-identity form flag.
    // 0x04 = IS_1, change to 0x00 (normal form with all-zero fields = invalid form).
    proof_blob[BQFC_FORM_SIZE] = 0x00;
    let result = check_proof_of_time_n_wesolowski(&d, &x_s, &proof_blob, ITERS, 0);
    assert!(!result, "corrupted proof should fail verification");
}
